### ISSUE TITLE
Uninstalling php, how?

### ISSUE THREAD

**Issue by laurentiuspurba** [mayflower/puppet-php#109]
Hello all,

Let say after successfully install this module, what is the best way to remove the whole module?

Please advise.

Thanks!
-Laurentius

**Comment by laurentiuspurba** [comment]
Any advise on this?

Basically, my use case is I want to remove/un-install this module that was installed wrongly in server. Is changing $ensure from 'present' to 'absent' in manifests/params.pp solves this?

Thanks!
-Laurentius

**Comment by mmoll** [comment]
sorry, this is not how puppet works :)

**Comment by fschndr** [comment]
Hello Laurentius,

there are good chances that puppet has used your systems package manager to install the packages needed in the module. Have a look in the module and find out the package names - then purge/uninstall theme manually or via puppets package resource. 

But i can't give you any guaranty that it's completely removed. Like @mmoll said "that is not how puppet works". It's possible to implement `absent` functionality in modules to remove them completely, but it's not practicable since there are so few cases where it's reasonable.

**Comment by globin** [comment]
Yes as @fschndr said, we don't implement `ensure => absent` specifically, as one can just set up a new correct machine when necessary.

That said it is possible that it works as is when setting this, but this is definitely not used by us and untested and the same strategy puppetlabs follows with most of its modules. If there are only small fixes necessary feel free to send a PR to make this work if it doesn't.
